export const FETCH_GOOGLE_SEARCH_STARTED = "FETCH_GOOGLE_SEARCH_STARTED";
export const FETCH_GOOGLE_SEARCH_SUCCESS = "FETCH_GOOGLE_SEARCH_SUCCESS";
export const FETCH_GOOGLE_SEARCH_FAILURE = "FETCH_GOOGLE_SEARCH_FAILURE";
export const FETCH_BING_SEARCH_STARTED = "FETCH_BING_SEARCH_STARTED";
export const FETCH_BING_SEARCH_SUCCESS = "FETCH_BING_SEARCH_SUCCESS";
export const FETCH_BING_SEARCH_FAILURE = "FETCH_BING_SEARCH_FAILURE";
export const CLEAN_BING_SEARCH = 'CLEAN_BING_SEARCH';
export const CLEAN_GOOGLE_SEARCH = 'CLEAN_GOOGLE_SEARCH';

export const searchTypes = {
  GOOGLE: 'Google',
  BING: 'Bing',
  BOTH: 'Both'
}